# Generated by Django 4.2 on 2023-04-17 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_kpi_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPISetting',
            fields=[
                ('value', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_kpi_setting', to=settings.AUTH_USER_MODEL)),
                ('kpi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpitype')),
            ],
        ),
        migrations.CreateModel(
            name='KPISet',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_kpi_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('value', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_kpi_report', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpitype')),
                ('kpi_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpiset')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
