# Generated by Django 4.1.1 on 2023-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpitype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
