# Generated by Django 4.1.1 on 2023-04-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_kpitype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitype',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
