# Generated by Django 4.1.1 on 2023-04-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_kpitype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpireport',
            name='kpi_set',
        ),
    ]
